<? $this->headTitle('Message Demo') ?>
<div>
    <h1>Message</h1>
    <p>
        Zym_Message provides an infrastructure to relay messages between 
        objects that don't necessarily know each other. This provides a loose 
        coupling between components and makes your app more flexible.
    </p>
    
    <div>
        <h2>Sandy</h2>
        <?= $this->action('notify-sandy', 'message', 'demo') ?>
    </div>
    
    <div>
        <h2>Bill</h2>
        <?= $this->action('notify-bill', 'message', 'demo') ?>
    </div>
</div>