<ul class="clearfix">
    <li class="pad">&nbsp;</li>
    
    <? $currentUri = rtrim($this->getRequest()->getRequestUri(), '/\\'); ?>
    <? foreach ($this->urls as $name => $url) : ?>
    <li class="<?= (end($this->urls) == $url) ? 'last' : '' ?>">
        <? if (strcasecmp($currentUri, rtrim($url, '/\\')) === 0) : ?>
        <strong>
            <a href="<?= $url; ?>"><?= $name; ?></a>
        </strong>
        <? else : ?>
        <a href="<?= $url; ?>"><?= $name; ?></a>
        <? endif; ?>
    </li>
    <? endforeach; ?>
</ul>