<? $this->headTitle('Home') ?>
<div>
    <h1>Welcome</h1>

    <div>
        <h2>Our first preview</h2>
        <p>
            We here at Zym thank you for testing Zym <?= Zym_Version::VERSION; ?>, this is our preview sandbox. 
            It was created in order to demonstrate the possibilities with Zym and to signify 
            a significant milestone in our roadmap. This preview is almost production ready 
            but API stability cannot be guaranteed; however, by releasing this preview,
            we hope to receive much needed feedback. Post comments or questions
            to our mailing list: <a href="http://groups.google.com/group/zym-framework">Zym Mailing List</a>.
        </p>
    </div>
    
    <div>
        <h2>So what is Zym anyways?</h2>
        
        <div>
            <h3>Background</h3>
            <p>
                Like many developers, we realized that using a framework can greatly improve
                your code quality and development time. Somewhere along the lines, we ended
                up using <a href="http://framework.zend.com">Zend Framework</a> because of its
                great code quality and design. During that time, the ZF did not have a large 
                community, the existence of <a href="http://www.zftalk.com">#zftalk</a> 
                allowed us collaborate on some common issues of ZF. With the release of ZF 1.5, 
                the community has grown to embrace the new framework as a heavy weight; however, 
                ZF still lacks vital aspects what many consider a traditional "framework".
            </p>
        </div>
        
        <div>
            <h3>Solving the issues</h3>
            <p>
                Many of us love ZF; however, it lacks in some area's and we ended up creating
                our own implementations to solve the issues. After realizing that many of us
                were just creating the same thing, we decided combine our efforts. 
                <a href="http://www.zym-project.com">Zym</a> aims to focus on the area's 
                that we believe ZF is actually lacking in.
            </p>
            
            <p>
                Overall, Zym to Zend Framework is similar to what 
                <a href="http://www.ubuntu.com">Ubuntu</a> is to Linux. Zym is a
                different flavor of ZF with its own niche in hopes that ZF stays
                light and clean like water. <b>Zym is not and does not intend to be
                a fork of ZF,</b> rather Zym's goal is to be a playground for things
                to come.
            </p>
        </div>
    </div>
</div>