<? $this->headTitle('Home') ?>
<div>
    <h1>Welcome</h1>

    <div>
        <h2>Our first preview</h2>
        <p>
            We here at Zym thank you for testing Zym 0.1PR, this is our preview sandbox. 
            It was created in order to demonstrate the possibilities with Zym and to signify 
            a significant milestone in our roadmap. This preview is nowhere near production ready 
            and API stability cannot be guaranteed; however, by releasing this preview,
            we hope to receive much needed feedback. Post comments or questions
            to our mailing list: <a href="http://groups.google.com/group/zym-framework">Zym Mailing List</a>.
        </p>
    </div>
    
    <div>
        <h2>So what is Zym anyways?</h2>
        
        <div>
            <h3>Background</h3>
            <p>
                Like many developers, we realized that using a framework can greatly improve
                your code quality and development time. Somewhere along the lines, we ended
                up using <a href="http://framework.zend.com">Zend Framework</a> because of its
                great code quality and design. During that time, the ZF did not have a large 
                community, but with the existence of <a href="http://www.zftalk.com">#zftalk</a> 
                we were able to collaborate on the common issues of ZF. With the release of ZF 1.5, 
                the community has grown to embrace it as a heavy weight; however, ZF still
                lacks vital aspects what many consider a "framework". This is mainly due to
                the process that it takes to release a quality product as it requires the
                community to review and voice its opinions.
            </p>
        </div>
        
        <div>
            <h3>ZF is "lacking"</h3>
            <p>
                ZF is not lacking, it covers the areas that it should. There is a point where
                a framework crosses the line and becomes too specific for all of its users.
                Many users are pushing for "ajax" and coupling with Javascript libraries.
                We feel that this should not be the direction of ZF, the community is full
                people with different needs; however, integration with client side libraries
                or code generation crosses the line between separation of client-side code
                from server-side.
            </p>
       </div>
        
        <div>
            <h3>Solving the issues</h3>
            <p>
                Many of us love ZF; however, it lacks in some area's and we ended up creating
                our own implementations to solve the issues. After realizing that many of us
                were just creating the same thing, we decided combine our efforts. 
                <a href="http://www.zym-project.com">Zym</a> aims to focus on the area's 
                that we believe ZF is actually lacking in and areas that we believe ZF should 
                not venture into.
            </p>
            
            <p>
                Overall, Zym to Zend Framework is similar to what 
                <a href="http://www.ubuntu.com">Ubuntu</a> is to Linux. Zym is a
                different flavor of ZF with its own niche in hopes that ZF stays
                light and clean like water.
            </p>
        </div>
    </div>
</div>