<?
$this->headTitle('Log Viewer');
$this->dojo()->requireModule('dijit.layout.BorderContainer')
             ->requireModule('dijit.layout.ContentPane')
             ->requireModule('dijit.layout.TabContainer')
             ->requireModule('dijit.Tree')
             ->requireModule('dojo.data.ItemFileReadStore');
?>
<div>
    <h1>Log Viewer</h1>

    <div dojoType="dijit.layout.BorderContainer" style="width: 100%; height: 500px;">
        <div dojoType="dijit.layout.ContentPane" region="center" style="padding: 10px;">
            Select a page from the archives or search for some content.
        </div>

        <div dojoType="dijit.layout.TabContainer" region="left" splitter="true" minSize="50" style="width: 200px;">
            <div dojoType="dijit.layout.ContentPane" title="Archive">
                <div dojoType="dojo.data.ItemFileReadStore" jsId="archiveStore" url="../data/format/json"></div>
                <div dojoType="dijit.tree.ForestStoreModel" jsId="archiveModel"
                     store="archiveStore"
                     rootId="archiveRoot" rootLabel="#zftalk.dev" childrenAttrs="children"></div>

                <div dojoType="dijit.Tree" model="archiveModel" openOnClick="true"></div>
            </div>

            <div dojoType="dijit.layout.ContentPane" title="Search">

            </div>
        </div>
    </div>
</div>