<? $this->headTitle('Demos') ?>
<div>
    <h1>Playground</h1>
    
    <p>
        Welcome to Zym's playground, below are links to various demos of Zym
        and/or Zend Framework's features. While these demo's are primary to
        demonstrate Zym, users of ZF can benefit greatly from them as many
        aspects are only slightly modified or unchanged.
    </p>
    
    <p>Playground areas:</p>
    <ul>
        <li>
            <a href="<?= $this->url(array('controller' => 'context-switch')) ?>">ContextSwitch</a>
        </li>
        <li>
            <a href="<?= $this->url(array('controller' => 'error')) ?>">Error</a>
        </li>
        <li>
            <a href="<?= $this->url(array('controller' => 'flash-messenger')) ?>">Flash Messenger</a>
        </li>
        <li>
            <a href="<?= $this->url(array('controller' => 'form')) ?>">Forms</a>
        </li>
        <li>
            <a href="<?= $this->url(array('controller' => 'navigation')) ?>">Navigation</a>
        </li>
        <li>
            <a href="<?= $this->url(array('controller' => 'notification')) ?>">Notification</a>
        </li>
        <li>
            <a href="<?= $this->url(array('controller' => 'paginate')) ?>">Pagination</a>
        </li>
        <li>
            <a href="<?= $this->url(array('controller' => 'translate')) ?>">Translation</a>
        </li>
    </ul>
</div>