<? $this->headTitle('Demos') ?>
<div>
    <h1>Playground</h1>

    <p>
        Welcome to Zym's playground, below are links to various demos of Zym
        and/or Zend Framework's features. While these demo's are primary to
        demonstrate Zym, users of ZF can benefit greatly from them as many
        aspects are only slightly modified or unchanged.
    </p>

    <p>Playground areas:</p>
    <?= $this->menu()->renderSubMenu(); ?>
</div>