<?= $this->xmlDeclaration() . "\n"; ?>
<?= $this->doctype() . "\n"; ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <!-- Start: Meta Tags -->
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <?= $this->headMeta() . "\n"; ?>
        <!-- End: Meta Tags -->
        
        <!-- Title -->
        <? $this->headTitle('Zym Framework')->setSeparator(' | ') ?>
        <?= $this->headTitle() . "\n"; ?>
        
        <!-- Start: Link Tags -->
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('styles/tools.css'); ?>" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('styles/typo.css');  ?>" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('styles/forms.css'); ?>" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('styles/layout-navtop-1col.css'); ?>" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('styles/layout.css'); ?>" />
        <?= $this->headLink() . "\n"; ?>
        
        <!--[if lte IE 6]>
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('zym/styles/ie/png-fix.css'); ?>" />
        <![endif]-->
        <!-- End: Link Tags -->
        
        <!-- Start: Styles -->
        <?= $this->headStyle() . "\n"; ?>
        <!-- End: Styles -->
        
        <!-- Start: Scripts -->
        <script type="text/javascript" src="http://o.aolcdn.com/dojo/1.1.1/dojo/dojo.xd.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl('scripts/app/layout.js'); ?>"></script>
        <script type="text/javascript">
        //<![CDATA[
            // Bootstrap
            app.layout.init();
        //]]>
        </script>
        
        <?= $this->headScript() . "\n"; ?>
        <!-- End: Scripts -->
    </head>
    
    <body>
        <div id="page">
            <!-- Start: Header -->
            <div id="header" class="clearfix">
                <!-- Start: Branding -->
                <div id="branding">
                    <h1>Zym Framework</h1>
                    <p>Add <em>flavor</em> to your ZF</p>
                </div>
                <!-- End: Branding -->
                
                <!-- Start: Search -->
                <!--
                <div id="search">
                    <form method="post" action="<?= $this->url(); ?>">
                        <div>
                            <label for="search-site">Search</label>
                            <input type="text" name="search" id="search-site" />
                            <input type="submit" value="Go" />
                        </div>
                    </form>
                </div>
                -->
                <!-- End: Search -->
            </div>
            <!-- End: Header -->
            
            <!-- Start: Content -->
            <div id="content" class="clearfix">
                <div id="main">
                    <div class="breadcrumbs">
                        <?= $this->breadcrumbs(); ?>
                    </div>

                    <div id="flash-container">
                        <? if (count($this->flashMessenger())) : ?>
                        <div id="flash">
                            <span>Message</span>
                            <?= $this->htmlList($this->flashMessenger()->getMessages()); ?>
                        </div>
                        <? endif; ?>
                    </div>
                    
                    <?/* Output content */?>
                    <?= $this->layout()->content . "\n"; ?>
                </div>
                
                <!-- Start: Navigation -->
                <div id="nav">
                    <div class="wrapper">
                        <h2 class="accessibility">Navigation</h2>
                        
                        <? $this->menu()->setUlClass('clearfix'); ?>
                        <?= "\n" . $this->menu()->toString(24); ?>
                    </div>
                </div>
                <!-- End: Navigation -->
            </div>
            <!-- End: Content -->
            
            <!-- Start: Footer -->
            <div id="footer" class="clearfix">
                <div id="divider">
                    <div />
                </div>
                
                <span class="left">
                    <a href="<?= $this->url(array(), 'default', true); ?>">Home</a>
                </span>
                
                <span class="right">
                    Copyright <?= date('Y'); ?> &copy; <a href="http://www.zym-project.com">Zym</a>
                </span>
            </div>
            <!-- End: Footer -->
        </div>

        <div id="extra1">&nbsp;</div>
        <div id="extra2">&nbsp;</div>
        
        <?= $this->inlineScript(); ?>
    </body>
</html>
<!-- This design was created by jugend from http://www.pluitsolutions.com -->