<? $this->headTitle('Paginate Demo') ?>
<div>
    <h1>Pagination</h1>
    
    <p>
        Pagination is an important aspect in displaying large data sets to the 
        user. This Zym component simplifies the process.
    </p>
    
    <div>
        <h2>Array</h2>
        
        <p>
            The Zym_Paginate_Array class allows simple pagination of array 
            data. <a href="<?= $this->url(array('action' => 'array')) ?>">Click Here</a>
        </p>
    </div>
</div>