<? $this->headTitle('Internal Error') ?>
<div>
    <h1>Opps, this problem's on us</h1>
    <p>
        Sorry, you haven't done anything wrong. It seems we have some small 
        bug problems at the moment, if your feeling in the mood, drop us a line 
        so we can get our bug squashing boots.
    </p>
    
    <div>
        <h2>What just happened?</h2>
        <p>
            It appears we encountered an internal server error referred in
            geek talk as an HTTP 500 Error. It most likely occured because of
            a bug in our code, incorrect server configuration or because we were
            unable to serve your request at the current time.
        </p>
    </div>
    
    <? if ($this->error instanceof Zym_Controller_Plugin_ErrorHandler_Data) : ?>
    <p>
        Reason: <?= $this->error->getException()->getMessage(); ?>
    </p>
    <? endif; ?>
</div>