<? $this->headTitle('Page cannot be found') ?>
<div>
    <h1>Opps!</h1>
    <p>
        Sorry, but the page you requested could not be found.
    </p>
    
    <p>
        We believe that this occured because of reasons such as, but not limited to:
    </p>
    
    <ul>
        <li>An incorrect url was provided</li>
        <li>The page got misplaced by our monkey</li>
        <li>It got eaten by the dik-diks</li>
        <li>The server is mad at you</li>
    </ul>
    
    <? if ($this->error instanceof Zym_Controller_Plugin_ErrorHandler_Data) : ?>
    <p>
        Reason: <?= $this->error->getException()->getMessage(); ?>
    </p>
    <? endif; ?>
</div>